import type { BlockStrategyTemplate } from './types'

export const DEFAULT_CONDITION_BLOCK_TEMPLATES: BlockStrategyTemplate[] = [
  {
    key: 'intraday_amount_surge_hold',
    name: '盘中放量拉升后站稳',
    description: '寻找盘中 15 分钟明显放量拉升, 随后半小时没有明显冲高回落的股票。',
    version: 4,
    enabled: true,
    executionMode: 'strict',
    scoreThreshold: 70,
    scope: {
      dateStart: '',
      dateEnd: '',
      lookbackDays: 5,
      stockPoolSources: ['allMarket', 'portfolio', 'trendWatchlist', 'chipMonitor'],
      excludeST: true,
      excludeBJ: false,
      minDailyAmount: null,
      dailyPrefilterLimit: 200,
      autoFetchMinuteLimit: 80,
      minuteFetchConcurrency: 1,
      minuteFetchIntervalMs: 1200,
      minuteFetchStopAfterFailures: 8,
    },
    root: {
      id: 'root',
      operator: 'AND',
      enabled: true,
      children: [
        {
          id: 'gain_15m',
          type: 'minute_window_gain',
          name: '15 分钟涨幅',
          description: '任意 15 分钟窗口涨幅不低于 3%。',
          enabled: true,
          weight: 25,
          hardRequired: true,
          params: { windowMinutes: 15, minGainPct: 3 },
        },
        {
          id: 'volume_ratio',
          type: 'minute_window_volume_ratio',
          name: '成交量放大',
          description: '拉升窗口成交量相对前 30 分钟均值不低于 1.8 倍。',
          enabled: true,
          weight: 20,
          hardRequired: true,
          params: { windowMinutes: 15, baselineMinutes: 30, minRatio: 1.8 },
        },
        {
          id: 'pullback',
          type: 'pullback_after_high',
          name: '高点后回撤',
          description: '命中窗口高点后 30 分钟最大回撤不超过 1.2%。',
          enabled: true,
          weight: 20,
          hardRequired: true,
          params: { afterMinutes: 30, maxPullbackPct: 1.2 },
        },
        {
          id: 'hold_ratio',
          type: 'hold_above_gain_ratio',
          name: '后续站稳比例',
          description: '后续 30 分钟至少保持拉升幅度的 65%。',
          enabled: true,
          weight: 20,
          params: { afterMinutes: 30, minHoldRatio: 65 },
        },
        {
          id: 'close_retention',
          type: 'close_retention',
          name: '收盘保持度',
          description: '收盘仍保持拉升幅度的 60% 以上。',
          enabled: true,
          weight: 15,
          params: { minRetentionPct: 60 },
        },
      ],
    },
  },
]
