import type { SourceRow } from './types'

type SeedSource = Omit<SourceRow, 'id' | 'lastScannedAt' | 'successRate'>


export const BUILT_IN_SOURCES: SeedSource[] = [
  // ── 监管机构 REGULATOR ──────────────────────────────────
  {
    nameCN: '中国证监会',
    nameEN: 'CSRC',
    url: 'http://www.csrc.gov.cn',
    feedUrl: null,
    category: 'REGULATOR',
    authorityWeight: 10,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.tab-content .szyw-lists:nth-of-type(1) ul li a, .tab-content .szyw-lists:nth-of-type(2) ul li a',
    financeSectionFilter: '/xinwen/',
    detailSelector: '.detail-news'
  },
  {
    nameCN: '中国人民银行',
    nameEN: 'PBOC',
    url: 'https://www.pbc.gov.cn',
    feedUrl: null,
    category: 'CENTRAL_BANK',
    authorityWeight: 10,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '#c_xwlist table td a',
    financeSectionFilter: '',
    detailSelector: ".portlet"
  },
  {
    nameCN: '国家发展和改革委员会',
    nameEN: 'NDRC',
    url: 'https://www.ndrc.gov.cn',
    feedUrl: null,
    category: 'GOVERNMENT',
    authorityWeight: 9,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: ".news.tabmenu ul li a",
    financeSectionFilter: '',
    detailSelector: null
  },
  {
    nameCN: '商务部',
    nameEN: 'MOFCOM',
    url: 'http://www.mofcom.gov.cn',
    feedUrl: null,
    category: 'GOVERNMENT',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.list-con li a, .news-box li a',
    financeSectionFilter: '/article/',
    detailSelector: null
  },
  {
    nameCN: '国家统计局',
    nameEN: 'NBS',
    url: 'http://www.stats.gov.cn',
    feedUrl: null,
    category: 'GOVERNMENT',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: ".wrapper-content1-right-list ul li a",
    financeSectionFilter: '',
    detailSelector: null
  },
  {
    nameCN: '财政部',
    nameEN: 'MOF',
    url: 'http://www.mof.gov.cn',
    feedUrl: null,
    category: 'GOVERNMENT',
    authorityWeight: 9,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.listTd a, .news-list td a',
    financeSectionFilter: '/zhengwuxinxi/',
    detailSelector: null
  },
  {
    nameCN: '国务院',
    nameEN: 'State Council',
    url: 'https://www.gov.cn',
    feedUrl: null,
    category: 'GOVERNMENT',
    authorityWeight: 10,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '#index_ywowen ul li a,#index_zxzc ul li a,.news-list li a',
    financeSectionFilter: '',
    detailSelector: '#UCAP-CONTENT'
  },
  // ── 官方媒体 STATE_MEDIA ─────────────────────────────────
  {
    nameCN: '新华社财经',
    nameEN: 'Xinhua Finance',
    url: 'http://www.xinhuanet.com/finance/',
    feedUrl: null,
    category: 'STATE_MEDIA',
    authorityWeight: 9,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: ".part2_l .part2_b .picTit a, .part2_r .list-style2 ul li a",
    financeSectionFilter: null,
    detailSelector: null
  },
  {
    nameCN: '人民日报财经',
    nameEN: "People's Daily Finance",
    url: 'http://finance.people.com.cn',
    feedUrl: null,
    category: 'STATE_MEDIA',
    authorityWeight: 9,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: ".news_box ul li a",
    financeSectionFilter: null,
    detailSelector: null
  },
  {
    nameCN: '中国金融时报',
    nameEN: 'Financial News',
    url: 'http://www.financialnews.com.cn',
    feedUrl: null,
    category: 'STATE_MEDIA',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.side-list ul li a',
    financeSectionFilter: null,
    detailSelector: null
  },
  // ── 金融媒体 FINANCIAL_PRESS ─────────────────────────────
  {
    nameCN: '中国证券报',
    nameEN: 'China Securities Journal',
    url: 'http://www.cs.com.cn',
    feedUrl: null,
    category: 'FINANCIAL_PRESS',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.list-01 ul li a, #root ul li a',
    financeSectionFilter: null,
    detailSelector: null
  },
  {
    nameCN: '上海证券报',
    nameEN: 'Shanghai Securities News',
    url: 'https://www.shobserver.com',
    feedUrl: null,
    category: 'FINANCIAL_PRESS',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.article-list li a, .news-box li a',
    financeSectionFilter: null,
    detailSelector: null
  },
  {
    nameCN: '证券时报',
    nameEN: 'Securities Times',
    url: 'https://www.stcn.com',
    feedUrl: null,
    category: 'FINANCIAL_PRESS',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: '.box-content ul li a,.top-news a,.cc-list a',
    financeSectionFilter: null,
    detailSelector: '.detail-content'
  },
  {
    nameCN: '财新网',
    nameEN: 'Caixin',
    url: 'https://finance.caixin.com/',
    feedUrl: null,
    category: 'FINANCIAL_PRESS',
    authorityWeight: 8,
    isBuiltIn: 1,
    isEnabled: 1,
    status: 'ACTIVE',
    parseStrategy: 'HTML_SCRAPE',
    contentSelector: "#listArticle a",
    financeSectionFilter: null,
    detailSelector: null
  },
  {
    nameCN: "21世纪经济报道",
    nameEN: "21st Century Business Herald",
    url: "https://www.21jingji.com",
    feedUrl: "",
    category: "FINANCIAL_PRESS",
    authorityWeight: 7,
    isBuiltIn: 1,
    isEnabled: 1,
    status: "ACTIVE",
    parseStrategy: "HTML_SCRAPE",
    contentSelector: ".news-list ul li a",
    financeSectionFilter: null,
    detailSelector: '.content'
  }
]
