import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8')
}

describe('FR-256 research agent renderer contract', () => {
  it('keeps contextual research explicit while adding a directly discoverable global workbench', () => {
    const analysis = source('src/components/AIAnalysis/AIAnalysis.tsx')
    const app = source('src/App.tsx')
    const workbench = source('src/components/AIAnalysis/DeepResearchWorkbench.tsx')
    expect(analysis).toContain('detail.discussion && (')
    expect(analysis).toContain('<ResearchAgentPanel')
    expect(analysis).toContain('draftQuestion={followUpInput}')
    expect(analysis).toContain('onClick={handleFollowUp}')
    expect(app).toContain("label: '深度研究'")
    expect(app).toContain("aiAnalysisSubTab === 'deepResearch'")
    expect(workbench).toContain('data-testid="deep-research-workbench"')
    expect(workbench).toContain('data-testid="deep-research-start"')
    expect(workbench).toContain('data-testid="direct-research-submit"')
    expect(workbench).toContain('researchAgent.startDirect')
    expect(workbench).not.toContain('startResearchDiscussion')
  })

  it('provides bounded, accessible controls and a responsive ledger surface', () => {
    const panel = source('src/components/AIAnalysis/ResearchAgentPanel.tsx')
    const manager = source('electron/main/services/researchAgentRunManager.ts')
    expect(panel).toContain('min-h-11')
    expect(panel).toContain('max-h-[40vh]')
    expect(panel).toContain('overflow-y-auto')
    expect(panel).toContain('motion-reduce:transition-none')
    expect(panel).toContain('role="dialog"')
    expect(panel).toContain('role="alert"')
    expect(panel).toContain("confirmedBudgetVersion: 'single-agent-unrestricted-v3'")
    expect(panel).toContain('模型或联网请求可能已经送达并产生费用')
    expect(panel).toContain('research-agent-plan')
    expect(panel).toContain('research-agent-model-calls')
    expect(panel).toContain('research-agent-evidence-policy')
    expect(panel).toContain('role="tablist"')
    expect(panel).toContain('role="tab"')
    expect(panel).toContain('role="tabpanel"')
    expect(panel).toContain('data-testid="research-agent-report-tab"')
    expect(panel).toContain('data-testid="research-agent-evidence-tab"')
    expect(panel).toContain("useState<'report' | 'evidence'>('report')")
    expect(panel.indexOf('data-testid="research-agent-report-tab"')).toBeLessThan(panel.indexOf('data-testid="research-agent-evidence-tab"'))
    expect(panel).toContain('research-agent-evidence-gate')
    expect(panel).toContain('research-agent-evidence-overview')
    expect(panel).toContain('research-agent-local-evidence')
    expect(panel).toContain('research-agent-network-evidence')
    expect(panel).toContain('research-agent-search-candidates')
    expect(panel).toContain('research-agent-document')
    expect(panel).toContain('research-agent-network-envelope')
    expect(panel).toContain('research-agent-remaining-unknowns')
    expect(panel).toContain('为什么需要联网')
    expect(panel).toContain('联网仍不足时继续使用已固化资料完成综合')
    expect(panel).toContain('联网仍不足时仅保留结论覆盖受限或形成受阻的结果')
    expect(panel).toContain('research-agent-execution-status')
    expect(panel).toContain('research-agent-conclusion-coverage')
    expect(panel).toContain('research-agent-conclusion-explanation')
    expect(panel).toContain('为什么结论覆盖受限：')
    expect(panel).not.toContain('部分完成')
    expect(manager).toContain("completed: '已完成'")
    expect(manager).toContain("conclusionLabel: '结论覆盖完整'")
    expect(manager).toContain("conclusionLabel: '结论覆盖受限'")
    expect(manager).toContain("conclusionLabel: '结论形成受阻'")
    expect(panel).toContain('effectiveSourceCount(toolCalls)')
    expect(panel).toContain('research-agent-cancel-dialog')
  })

  it('exposes only lifecycle/read methods through preload', () => {
    const preload = source('electron/preload/index.ts')
    const start = preload.indexOf('researchAgent: {')
    const end = preload.indexOf('researchAccess: {', start)
    const contract = preload.slice(start, end)
    for (const method of ['preflight:', 'preflightDirect:', 'startRun:', 'startDirect:', 'startReview:', 'listRuns:', 'getRun:', 'cancelRun:', 'resumeRun:', 'retryRun:', 'deleteRun:', 'onProgress:']) {
      expect(contract).toContain(method)
    }
    expect(contract).not.toContain('callTool')
    expect(contract).not.toContain('callModel')
    expect(contract).not.toContain('apiKey')
    expect(contract).not.toContain('leaseOwner')
  })

  it('keeps the direct launcher bounded, recoverable and accessible', () => {
    const workbench = source('src/components/AIAnalysis/DeepResearchWorkbench.tsx')
    expect(workbench).toContain('min-h-11')
    expect(workbench).toContain('motion-reduce:transition-none')
    expect(workbench).toContain('role="dialog"')
    expect(workbench).toContain('role="alert"')
    expect(workbench).toContain('aria-pressed')
    expect(workbench).toContain('researchAgent.listRuns(null)')
    expect(workbench).toContain('matchesRunFilter(run, filterRef.current)')
    expect(workbench).toContain('onOpenDiscussion=')
    expect(workbench).toContain("confirmedBudgetVersion: 'single-agent-unrestricted-v3'")
    expect(workbench).toContain('data-testid="deep-research-progress"')
    expect(workbench).toContain('testId="deep-research-retry-dialog"')
    expect(workbench).toContain('testId="deep-research-delete-dialog"')
    expect(workbench).toContain('其他重试记录会保留')
    expect(workbench).toContain('aria-live="polite"')
    expect(workbench).toContain('打开 AI 配置')
    expect(workbench).toContain('项目读取失败')
    expect(workbench).toContain('<ResearchCombobox')
    expect(workbench).toContain('testId="direct-research-project"')
    expect(workbench).toContain('searchPlaceholder="搜索产业研究项目"')
    expect(workbench).not.toContain('<select value={projectId}')
    expect(workbench).toContain('role="alert"')
    expect(source('src/components/AIAnalysis/ResearchAgentPanel.tsx')).toContain("run.status !== 'failed' || run.retryable")
  })

  it('renders the evidence-bound multi-perspective lifecycle without exposing execution controls', () => {
    const panel = source('src/components/AIAnalysis/ResearchAgentPanel.tsx')
    expect(panel).toContain("confirmedBudgetVersion: 'multi-perspective-unrestricted-v2'")
    expect(panel).toContain('模型调用按研究需要')
    expect(panel).toContain('research-agent-start-review')
    expect(panel).toContain('research-agent-review-dialog')
    expect(panel).toContain('research-agent-multi-perspective')
    expect(panel).toContain('research-agent-multi-perspective-evidence')
    expect(panel).toContain('<MultiPerspectiveReport detail={detail} />')
    expect(panel).toContain('<MultiPerspectiveEvidence detail={detail} />')
    expect(panel).toContain('research-agent-bull')
    expect(panel).toContain('research-agent-bear')
    expect(panel).toContain('research-agent-consensus')
    expect(panel).toContain('research-agent-disagreements')
    expect(panel).toContain('research-agent-unknowns')
    expect(panel).toContain('research-agent-verification-checklist')
    expect(panel).toContain('research-agent-quality-summary')
    expect(panel).toContain('不会再次联网')
    expect(panel).not.toContain('callRole')
  })
})
